### ISSUE TITLE
CircleCI Partner Review

### ISSUE THREAD

**Issue by KyleTryon** [PractiTest/firecracker-orb#5]
Hello,
My name is Kyle Tryon from the community and partner engineering team at CircleCI. Thank you for sending in your Orb. We have taken a look and have a short list of requested changes to prepare for partnership.

**Missing items:**
 * Usage examples:
     * https://circleci.com/docs/2.0/orbs-best-practices/#examples
     * example: https://github.com/CircleCI-Public/github-cli-orb/tree/main/src/examples

**Required change:**
* Never request an API key directly as a string, instead use the env_var_name type.
    * https://circleci.com/docs/2.0/reusing-config/#environment-variable-name
* Missing usage examples

**Suggested changes:**
* Consider reducing the number of steps within your command.
    * More steps means more in the UI. Many steps here can likely be combined into a longer single step.
* Update the description
    * Include information about what problem your orb solves so that new users who are searching for solutions may stumble upon it.
* Update README.md

When all updates are ready let us know and before the orb is fully available we'll want to ensure version 1.0.0 is available.

**Comment by shmuelko** [comment]
@KyleTryon hey, I changed the code accordingly to your request, check main, please
https://circleci.com/developer/orbs/orb/practitest/firecracker?version=0.0.26

**Comment by brivu** [comment]
> @KyleTryon hey, I changed the code accordingly to your request, check main, please
> https://circleci.com/developer/orbs/orb/practitest/firecracker?version=0.0.26

Hey @shmuelko! 

Thanks for your response.  I'm Brian from the CircleCI's Community and Partner Engineering team.  

I took a look over your changes and have a couple of small tweaks.  In your usage example, you list api_token as a parameter with FIRE_API_TOKEN as it's value.  I know you've listed the api_token as env_var_name and it's required but to avoid confusion, can you please add FIRE_API_TOKEN as the default value? 

When you're ready to publish the orb, please publish version 1.0.0 by adding ' [semver:major] ' to the title of this PR.  

Thanks! 
Brian

**Comment by shmuelko** [comment]
Hey @brivu,

Changed api_token parameter to have default as you requested.

Please let me know if this is orb ready.

About the major version before the final release that goes without saying.

Regards,
Shmuel

**Comment by brivu** [comment]
Hi @shmuelko, 

I just wanted to close this loop in case you haven't noticed.  This orb has been published and has been certified as a Partner.  

Let me know if there's anything else you need! 

Best, 
Brian
